// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBheZpG2QCtBrBspDi0ns_OWWAGWkSNMYw',
    appId: '1:583335541663:web:848c56d79894a07f219baa',
    messagingSenderId: '583335541663',
    projectId: 'supply-20735',
    authDomain: 'supply-20735.firebaseapp.com',
    storageBucket: 'supply-20735.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBO5rUcDeWOAqr4mfx2HGiBpYc-hxGZ5Lk',
    appId: '1:583335541663:android:99cc30195a6497b6219baa',
    messagingSenderId: '583335541663',
    projectId: 'supply-20735',
    storageBucket: 'supply-20735.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCGTyCIqOHeV6IpsKRsDMymXPKeEKrw_QQ',
    appId: '1:583335541663:ios:adb311e13a42ff55219baa',
    messagingSenderId: '583335541663',
    projectId: 'supply-20735',
    storageBucket: 'supply-20735.firebasestorage.app',
    iosBundleId: 'com.falcon.Supplier',
  );
}
